services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
